[program:mariadb]
command=/usr/sbin/mariadbd --datadir=/var/lib/mysql --user=mysql --socket=/run/mysqld/mysqld.sock
priority=10
autostart=true
autorestart=true
startretries=20
stdout_logfile=/var/log/supervisor/mariadb.log
stderr_logfile=/var/log/supervisor/mariadb.err
