[program:redis]
command=/usr/bin/redis-server --appendonly yes --dir /var/lib/redis
priority=20
autostart=true
autorestart=true
startretries=20
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis.err
