[program:redis]
command=/usr/local/bin/run-redis.sh
priority=20
autostart=false
autorestart=true
startretries=20
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis.err
