[program:backend]
command=/usr/local/bin/run-backend.sh
user=frappe
priority=50
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/backend.log
stderr_logfile=/var/log/supervisor/backend.err

[program:websocket]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
user=frappe
priority=60
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/websocket.log
stderr_logfile=/var/log/supervisor/websocket.err

[program:worker]
command=/usr/local/bin/run-worker.sh
directory=/home/frappe/frappe-bench
user=frappe
priority=70
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/worker.log
stderr_logfile=/var/log/supervisor/worker.err

[program:scheduler]
command=bench schedule
directory=/home/frappe/frappe-bench
user=frappe
priority=80
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/scheduler.log
stderr_logfile=/var/log/supervisor/scheduler.err

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
priority=90
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.err
stopsignal=INT
