[program:backend]
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=127.0.0.1:8000 --threads=4 --workers=2 --worker-class=gthread --worker-tmp-dir=/dev/shm --timeout=120 --preload frappe.app:application
user=frappe
priority=50
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/backend.log
stderr_logfile=/var/log/supervisor/backend.err

[program:websocket]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
user=frappe
priority=60
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/websocket.log
stderr_logfile=/var/log/supervisor/websocket.err

[program:worker]
command=bench worker --queue long,default,short
directory=/home/frappe/frappe-bench
user=frappe
priority=70
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/worker.log
stderr_logfile=/var/log/supervisor/worker.err

[program:scheduler]
command=bench schedule
directory=/home/frappe/frappe-bench
user=frappe
priority=80
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/scheduler.log
stderr_logfile=/var/log/supervisor/scheduler.err

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
priority=90
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.err
stopsignal=INT
