from __future__ import annotations

from typing import Any

BIZ_MODE_PURCHASE_REQUEST = "采购申请"
BIZ_MODE_REIMBURSEMENT_REQUEST = "报销申请"
BIZ_MODE_TELEGRAPHIC_TRANSFER_REQUEST = "电汇申请"
BIZ_MODE_MONTH_END_SUPPLEMENT = "月结补录"

ALLOWED_BIZ_MODES = [
    BIZ_MODE_PURCHASE_REQUEST,
    BIZ_MODE_REIMBURSEMENT_REQUEST,
    BIZ_MODE_TELEGRAPHIC_TRANSFER_REQUEST,
    BIZ_MODE_MONTH_END_SUPPLEMENT,
]

BIZ_MODE_OPTIONS = "\n".join(ALLOWED_BIZ_MODES)

LEGACY_BIZ_MODE_MAP = {
    "常规采购": BIZ_MODE_PURCHASE_REQUEST,
    "直接采购": BIZ_MODE_PURCHASE_REQUEST,
    "员工代付": BIZ_MODE_REIMBURSEMENT_REQUEST,
    "无发票现金支付": BIZ_MODE_REIMBURSEMENT_REQUEST,
    "其他账户支付": BIZ_MODE_REIMBURSEMENT_REQUEST,
    "自办电汇": BIZ_MODE_TELEGRAPHIC_TRANSFER_REQUEST,
    BIZ_MODE_PURCHASE_REQUEST: BIZ_MODE_PURCHASE_REQUEST,
    BIZ_MODE_REIMBURSEMENT_REQUEST: BIZ_MODE_REIMBURSEMENT_REQUEST,
    BIZ_MODE_TELEGRAPHIC_TRANSFER_REQUEST: BIZ_MODE_TELEGRAPHIC_TRANSFER_REQUEST,
    BIZ_MODE_MONTH_END_SUPPLEMENT: BIZ_MODE_MONTH_END_SUPPLEMENT,
}


def normalize_biz_mode(value: Any, default: str | None = None) -> str | None:
    if value in (None, ""):
        return default

    normalized = LEGACY_BIZ_MODE_MAP.get(str(value).strip(), str(value).strip())
    return normalized if normalized in ALLOWED_BIZ_MODES else default


def is_allowed_biz_mode(value: Any) -> bool:
    return normalize_biz_mode(value) in ALLOWED_BIZ_MODES
