name: Build ERPNext AIO Image

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 推 GHCR 需要
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive tags
        id: meta
        run: |
          IMAGE_NAME_GHCR="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/erpnext15-aio"
          TAGS_GHCR="${IMAGE_NAME_GHCR}:latest"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS_GHCR="${TAGS_GHCR},${IMAGE_NAME_GHCR}:${GITHUB_REF_NAME}"
          fi
          echo "ghcr=${TAGS_GHCR}" >> "$GITHUB_OUTPUT"

          if [[ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]]; then
            IMAGE_NAME_DH="${{ secrets.DOCKERHUB_USERNAME }}/erpnext15-aio"
            TAGS_DH="${IMAGE_NAME_DH}:latest"
            if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
              TAGS_DH="${TAGS_DH},${IMAGE_NAME_DH}:${GITHUB_REF_NAME}"
            fi
            echo "dh=${TAGS_DH}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: erpnext15/aio/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.ghcr }}
          build-args: |
            CHINA_MIRRORS=no
            FRAPPE_BRANCH=version-15
            ERPNEXT_BRANCH=version-15
            SITE_NAME=site1.local
            ADMIN_PASSWORD=admin
            SITE_DB_PASSWORD=Pass1234
            MARIADB_ROOT_PASSWORD=Pass1234

      - name: Build and push (DockerHub) - optional
        if: ${{ steps.meta.outputs.dh != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: erpnext15/aio/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.dh }}
          build-args: |
            CHINA_MIRRORS=no
            FRAPPE_BRANCH=version-15
            ERPNEXT_BRANCH=version-15
            SITE_NAME=site1.local
            ADMIN_PASSWORD=admin
            SITE_DB_PASSWORD=Pass1234
            MARIADB_ROOT_PASSWORD=Pass1234
